### PR TITLE
Add godep support and code review powered by goreport

### PR DESCRIPTION
**Pull request by gaocegege**
CR, please.
@gaocegege

### CODE REVIEW

**Comment by gaocegege** [comment]
LGTM, awesome work :+1:

**Comment by at15** [comment]
it seems go1.6 is going to support vendor?

**Comment by gaocegege** [comment]
@at15 嗯，文档应该需要update

**Comment by at15** [comment]
@gaocegege 你不update我就不写了，哼 (update了我也写不了.....

**Pull request merged**
