### PR TITLE
WIP: Add Mail Service

### PR DESCRIPTION
**Pull request by gaocegege**
try to solve #25

### CODE REVIEW

**Comment by gaocegege** [comment]
填坑达人！@gaocegege

**Comment by gaocegege** [comment]
re @gaocegege 过奖过奖

**Comment by at15** [comment]
@gaocegege \w/ awesome

**Comment by gaocegege** [comment]
challenge:
1. [mailgun/mailgun-go](https://github.com/mailgun/mailgun-go)需要两个key，跟书里写好的不一样

**Pull request closed without merging**
